{
	name: "Calculate Basic Interest Amnesty",
	template: "calculate-basicint-amnesty",
	params: [
		{ name:"ledger", datatype:'RPTLedgerFact', usevar:true, caption:'Ledger ID', required:true },
		{ name: "expr", datatype: 'string', caption: 'Computation Formula', expression:true },
	]
}