/*
 * RPTReceiptAddManualItemPage.java
 *
 * Created on November 3, 2013, 7:26 PM
 */

package com.rameses.gov.etracs.rpt.collection.ui;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  Rameses
 */
@Template(FormPage.class)
@StyleSheet
public class RPTReceiptNoLedgerAddPage extends javax.swing.JPanel {
    
    /** Creates new form RPTReceiptAddManualItemPage */
    public RPTReceiptNoLedgerAddPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xFormPanel5 = new com.rameses.rcp.control.XFormPanel();
        xComboBox4 = new com.rameses.rcp.control.XComboBox();
        xComboBox7 = new com.rameses.rcp.control.XComboBox();
        xFormPanel4 = new com.rameses.rcp.control.XFormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xComboBox5 = new com.rameses.rcp.control.XComboBox();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xIntegerField2 = new com.rameses.rcp.control.XIntegerField();
        xComboBox6 = new com.rameses.rcp.control.XComboBox();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();
        xButton1 = new com.rameses.rcp.control.XButton();
        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        xFormPanel6 = new com.rameses.rcp.control.XFormPanel();
        xDecimalField2 = new com.rameses.rcp.control.XDecimalField();

        setPreferredSize(new java.awt.Dimension(841, 528));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Manual Ledger Information");
        xFormPanel1.setBorder(xTitledBorder1);
        xFormPanel1.setPadding(new java.awt.Insets(5, 5, 5, 5));
        xTextField1.setCaption("TD No.");
        xTextField1.setCaptionWidth(100);
        xTextField1.setIndex(-10);
        xTextField1.setName("entity.tdno");
        xTextField1.setPreferredSize(new java.awt.Dimension(220, 20));
        xTextField1.setRequired(true);
        xFormPanel1.add(xTextField1);

        xTextField2.setCaption("PIN");
        xTextField2.setCaptionWidth(100);
        xTextField2.setName("entity.pin");
        xTextField2.setPreferredSize(new java.awt.Dimension(220, 20));
        xTextField2.setRequired(true);
        xFormPanel1.add(xTextField2);

        xFormPanel5.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel5.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel5.setPreferredSize(new java.awt.Dimension(0, 22));
        xFormPanel5.setShowCaption(false);
        xComboBox4.setCaption("Transaction Type");
        xComboBox4.setCaptionWidth(100);
        xComboBox4.setCellPadding(new java.awt.Insets(0, 0, 0, 10));
        xComboBox4.setExpression("#{item.objid}");
        xComboBox4.setItems("txntypes");
        xComboBox4.setName("entity.txntype");
        xComboBox4.setPreferredSize(new java.awt.Dimension(65, 20));
        xFormPanel5.add(xComboBox4);

        xComboBox7.setCaption("Type");
        xComboBox7.setCaptionWidth(50);
        xComboBox7.setExpression("#{item.code}");
        xComboBox7.setItems("rputypes");
        xComboBox7.setName("entity.rputype");
        xComboBox7.setPreferredSize(new java.awt.Dimension(92, 20));
        xComboBox7.setRequired(true);
        xFormPanel5.add(xComboBox7);

        xFormPanel1.add(xFormPanel5);

        xFormPanel4.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel4.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel4.setPreferredSize(new java.awt.Dimension(0, 22));
        xFormPanel4.setShowCaption(false);
        xComboBox1.setCaption("Classification");
        xComboBox1.setCaptionWidth(100);
        xComboBox1.setCellPadding(new java.awt.Insets(0, 0, 0, 10));
        xComboBox1.setExpression("#{item.code}");
        xComboBox1.setItems("classifications");
        xComboBox1.setName("entity.classification");
        xComboBox1.setPreferredSize(new java.awt.Dimension(65, 20));
        xComboBox1.setRequired(true);
        xFormPanel4.add(xComboBox1);

        xComboBox2.setCaption("Actual Use");
        xComboBox2.setCaptionWidth(80);
        xComboBox2.setExpression("#{item.code}");
        xComboBox2.setItems("classifications");
        xComboBox2.setName("entity.actualuse");
        xComboBox2.setPreferredSize(new java.awt.Dimension(62, 20));
        xComboBox2.setRequired(true);
        xFormPanel4.add(xComboBox2);

        xFormPanel1.add(xFormPanel4);

        xComboBox3.setCaption("Barangay");
        xComboBox3.setCaptionWidth(100);
        xComboBox3.setExpression("#{item.name}");
        xComboBox3.setItems("barangays");
        xComboBox3.setName("entity.barangay");
        xComboBox3.setPreferredSize(new java.awt.Dimension(220, 20));
        xComboBox3.setRequired(true);
        xFormPanel1.add(xComboBox3);

        xDecimalField1.setCaption("Assessed Value");
        xDecimalField1.setCaptionWidth(100);
        xDecimalField1.setName("entity.av");
        xDecimalField1.setPreferredSize(new java.awt.Dimension(220, 20));
        xDecimalField1.setRequired(true);
        xFormPanel1.add(xDecimalField1);

        xFormPanel2.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel2.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel2.setPreferredSize(new java.awt.Dimension(0, 22));
        xFormPanel2.setShowCaption(false);
        xIntegerField1.setCaption("From Year");
        xIntegerField1.setCaptionWidth(100);
        xIntegerField1.setCellPadding(new java.awt.Insets(0, 0, 0, 10));
        xIntegerField1.setName("entity.fromyear");
        xIntegerField1.setPreferredSize(new java.awt.Dimension(65, 20));
        xIntegerField1.setRequired(true);
        xFormPanel2.add(xIntegerField1);

        xComboBox5.setCaption("Qtr.");
        xComboBox5.setCaptionWidth(50);
        xComboBox5.setExpression("#{item.code}");
        xComboBox5.setItems("quarters");
        xComboBox5.setName("entity.fromqtr");
        xComboBox5.setPreferredSize(new java.awt.Dimension(92, 20));
        xComboBox5.setRequired(true);
        xFormPanel2.add(xComboBox5);

        xFormPanel1.add(xFormPanel2);

        xFormPanel3.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel3.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel3.setPreferredSize(new java.awt.Dimension(0, 22));
        xFormPanel3.setShowCaption(false);
        xIntegerField2.setCaption("To Year");
        xIntegerField2.setCaptionWidth(100);
        xIntegerField2.setCellPadding(new java.awt.Insets(0, 0, 0, 10));
        xIntegerField2.setName("entity.toyear");
        xIntegerField2.setPreferredSize(new java.awt.Dimension(65, 20));
        xIntegerField2.setRequired(true);
        xFormPanel3.add(xIntegerField2);

        xComboBox6.setCaption("Qtr.");
        xComboBox6.setCaptionWidth(50);
        xComboBox6.setExpression("#{item.code}");
        xComboBox6.setItems("quarters");
        xComboBox6.setName("entity.toqtr");
        xComboBox6.setPreferredSize(new java.awt.Dimension(92, 20));
        xComboBox6.setRequired(true);
        xFormPanel3.add(xComboBox6);

        xFormPanel1.add(xFormPanel3);

        xSeparator1.setPreferredSize(new java.awt.Dimension(0, 20));
        javax.swing.GroupLayout xSeparator1Layout = new javax.swing.GroupLayout(xSeparator1);
        xSeparator1.setLayout(xSeparator1Layout);
        xSeparator1Layout.setHorizontalGroup(
            xSeparator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );
        xSeparator1Layout.setVerticalGroup(
            xSeparator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        xFormPanel1.add(xSeparator1);

        xButton1.setMnemonic('c');
        xButton1.setName("calculateDue");
        xButton1.setShowCaption(false);
        xButton1.setText("Calculate Due");
        xFormPanel1.add(xButton1);

        xDataTable1.setColumns(new com.rameses.rcp.common.Column[]{
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "year"}
                , new Object[]{"caption", "Year"}
                , new Object[]{"width", 60}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", false}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.UPPER}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.IntegerColumnHandler(null, -1, -1)}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "qtr"}
                , new Object[]{"caption", "Qtr"}
                , new Object[]{"width", 50}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", false}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.UPPER}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "basic"}
                , new Object[]{"caption", "Basic"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.UPPER}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.DecimalColumnHandler("#,##0.00", -1.0, -1.0, false, 2)}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "basicdisc"}
                , new Object[]{"caption", "Discount"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.UPPER}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.DecimalColumnHandler("#,##0.00", -1.0, -1.0, false, 2)}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "basicint"}
                , new Object[]{"caption", "Interest"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.UPPER}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.DecimalColumnHandler("#,##0.00", -1.0, -1.0, false, 2)}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "sef"}
                , new Object[]{"caption", "SEF"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.UPPER}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.DecimalColumnHandler("#,##0.00", -1.0, -1.0, false, 2)}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "sefdisc"}
                , new Object[]{"caption", "Discount"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.UPPER}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.DecimalColumnHandler("#,##0.00", -1.0, -1.0, false, 2)}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "sefint"}
                , new Object[]{"caption", "Interest"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.UPPER}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.DecimalColumnHandler("#,##0.00", -1.0, -1.0, false, 2)}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "firecode"}
                , new Object[]{"caption", "Fire Code"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", true}
                , new Object[]{"editableWhen", null}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.UPPER}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.DecimalColumnHandler("#,##0.00", -1.0, -1.0, false, 2)}
            }),
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "amount"}
                , new Object[]{"caption", "Amount"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.UPPER}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.DecimalColumnHandler("#,##0.00", -1.0, -1.0, false, 2)}
            })
        });
        xDataTable1.setHandler("listHandler");

        xDecimalField2.setCaption("Amount Due");
        xDecimalField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        xDecimalField2.setEnabled(false);
        xDecimalField2.setFont(new java.awt.Font("Courier New", 1, 14));
        xDecimalField2.setName("entity.ledger.amount");
        xDecimalField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel6.add(xDecimalField2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(xDataTable1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                    .addComponent(xFormPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                    .addComponent(xFormPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xDataTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XComboBox xComboBox4;
    private com.rameses.rcp.control.XComboBox xComboBox5;
    private com.rameses.rcp.control.XComboBox xComboBox6;
    private com.rameses.rcp.control.XComboBox xComboBox7;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XDecimalField xDecimalField2;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XFormPanel xFormPanel4;
    private com.rameses.rcp.control.XFormPanel xFormPanel5;
    private com.rameses.rcp.control.XFormPanel xFormPanel6;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XIntegerField xIntegerField2;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    // End of variables declaration//GEN-END:variables
    
}
