package bpassessment;

declare BPApplication
	orgtype:		String
	officetype:		String
	apptype:		String
	txnmode:		String
	barangayid:		String
end

declare LOB 
	objid: 			String
	lobid:			String
	name:			String
	classification: 	String
	attributes:			String
	assessmenttype:		String
end

declare BusinessInfo 
	objid: 			String
	lob:			LOB
	name:			String
	stringvalue:	String
	intvalue:		int
	booleanvalue:	boolean
	decimalvalue:	double
end

declare TaxFeeAccount 
	objid:			String
	acctid:			String
	type:			String
	lob:			LOB	
	name:			String
	amount:			double
	highest:		boolean
	lowest:			boolean
	assessedvalue:	double
	data:			Object
end 

declare SysVariable 
	objid:			String
	lob:			LOB
	name:			String
	stringvalue:	String
	intvalue:		int
	booleanvalue:	boolean
	decimalvalue:	double
end

