package bpassessment;

declare BPApplication
	orgtype:		String
	officetype:		String
	apptype:		String
	barangayid:		String
end

declare LOB 
	objid: 			String
	lobid:			String
	name:			String
	classification: 	String
	attributes:			String
	assessmenttype:		String
end

declare StringBusinessInfo 
	objid: 		String
	lob:		LOB
	name:		String
	value:		String
end

declare DecimalBusinessInfo 
	objid: 		String
	lob:		LOB
	name:		String
	value:		double
end

declare IntegerBusinessInfo 
	objid: 			String
	lob:			LOB
	name:			String
	value:			int
end

declare BooleanBusinessInfo 
	objid: 				String
	lob:				LOB
	name:				String
	value:			boolean
end

declare BusinessTax 
	objid:			String
	acctid:			String
	lob:			LOB	
	name:			String
	amount:			double
	assessedvalue:	double
	highest:		boolean
	lowest:			boolean
	data:			Object
end 

declare RegFee 
	objid:			String
	acctid:			String
	lob:			LOB	
	name:			String
	amount:			double
	assessedvalue:	double
	highest:		boolean
	lowest:			boolean
	data:			Object
end 

declare OtherCharge 
	objid:			String
	acctid:			String
	lob:			LOB	
	name:			String
	amount:			double
	assessedvalue:	double
	highest:		boolean
	lowest:			boolean
	data:			Object
end 
