/*
 * CollectionInitialPage.java
 *
 * Created on March 13, 2013, 10:49 AM
 */

package com.rameses.enterprise.treasury.collection.ui;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  rameses
 */
@StyleSheet
@Template(FormPage.class)
public class CollectionInitPage extends javax.swing.JPanel {
    
    /** Creates new form CollectionInitialPage */
    public CollectionInitPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        btnBarcode = new com.rameses.rcp.control.XButton();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Initial Collection Information");
        formPanel1.setBorder(xTitledBorder1);
        xComboBox1.setAllowNull(false);
        xComboBox1.setCaption("AF No.");
        xComboBox1.setCaptionWidth(100);
        xComboBox1.setExpression("#{caption}");
        xComboBox1.setFont(new java.awt.Font("Arial", 1, 12));
        xComboBox1.setImmediate(true);
        xComboBox1.setItems("collectionforms");
        xComboBox1.setName("collectionform");
        xComboBox1.setPreferredSize(new java.awt.Dimension(80, 22));
        xComboBox1.setRequired(true);
        formPanel1.add(xComboBox1);

        xComboBox3.setCaption("Collector");
        xComboBox3.setCaptionWidth(100);
        xComboBox3.setExpression("#{name}");
        xComboBox3.setFont(new java.awt.Font("Arial", 1, 11));
        xComboBox3.setImmediate(true);
        xComboBox3.setItems("collectorlist");
        xComboBox3.setName("collector");
        xComboBox3.setPreferredSize(new java.awt.Dimension(0, 22));
        xComboBox3.setRequired(true);
        formPanel1.add(xComboBox3);

        xComboBox2.setCaption("Collection Type");
        xComboBox2.setCaptionWidth(100);
        xComboBox2.setDepends(new String[] {"collectionform"});
        xComboBox2.setDynamic(true);
        xComboBox2.setExpression("#{caption}");
        xComboBox2.setFont(new java.awt.Font("Arial", 1, 12));
        xComboBox2.setItems("collectionhandlers");
        xComboBox2.setName("collectionhandler");
        xComboBox2.setPreferredSize(new java.awt.Dimension(0, 22));
        xComboBox2.setRequired(true);
        formPanel1.add(xComboBox2);

        xLabel4.setFont(new java.awt.Font("Arial", 1, 18));
        xLabel4.setForeground(new java.awt.Color(204, 0, 0));
        xLabel4.setName("txnmode");

        btnBarcode.setMnemonic('b');
        btnBarcode.setAccelerator("F8");
        btnBarcode.setImmediate(true);
        btnBarcode.setName("readBarcode");
        btnBarcode.setText("Scan Barcode");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(xLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 558, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btnBarcode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 345, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(xLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnBarcode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XButton btnBarcode;
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XLabel xLabel4;
    // End of variables declaration//GEN-END:variables
    
}
