/*
 * CollectionPage.java
 *
 * Created on March 13, 2013, 1:52 PM
 */

package com.rameses.enterprise.treasury.collection.ui;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import java.awt.Component;
import java.math.BigDecimal;
import javax.swing.JComponent;

/**
 *
 * @author  rameses
 */
@StyleSheet
@Template(FormPage.class)
public class CollectionPage extends javax.swing.JPanel {
    
    /** Creates new form CollectionPage */
    public CollectionPage() {
        initComponents();
        panelRight.putClientProperty("reserved", "true");
        bodyPanel.putClientProperty("reserved", "true");
    }

    public Component add(Component comp) {
        String s = ((JComponent) comp).getClientProperty("reserved")+"";
        if ("true".equals(s)) {
            return super.add(comp);
        }
        else {
            return bodyPanel.add(comp); 
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        panelRight = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        jLabel4 = new javax.swing.JLabel();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        jLabel5 = new javax.swing.JLabel();
        xNumberField3 = new com.rameses.rcp.control.XNumberField();
        jPanel5 = new javax.swing.JPanel();
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        jLabel6 = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        paymentsummaryPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        stubinfoPanel = new com.rameses.rcp.util.FormPanel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xLabel10 = new com.rameses.rcp.control.XLabel();
        xLabel8 = new com.rameses.rcp.control.XLabel();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(884, 487));
        panelRight.setLayout(null);

        panelRight.setMinimumSize(new java.awt.Dimension(101, 100));
        panelRight.setPreferredSize(new java.awt.Dimension(230, 100));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setText("Amount Due:");
        panelRight.add(jLabel3);
        jLabel3.setBounds(12, 14, 158, 20);

        xNumberField1.setFieldType(BigDecimal.class);
        xNumberField1.setFont(new java.awt.Font("Tahoma", 1, 24));
        xNumberField1.setIndex(100);
        xNumberField1.setName("entity.info.amount");
        xNumberField1.setPattern("#,##0.00");
        xNumberField1.setReadonly(true);
        panelRight.add(xNumberField1);
        xNumberField1.setBounds(12, 38, 206, 48);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel4.setText("Total Payment:");
        panelRight.add(jLabel4);
        jLabel4.setBounds(12, 92, 206, 20);

        xNumberField2.setEditable(false);
        xNumberField2.setFieldType(BigDecimal.class);
        xNumberField2.setFont(new java.awt.Font("Tahoma", 1, 24));
        xNumberField2.setIndex(100);
        xNumberField2.setName("entity.info.totalpayment");
        xNumberField2.setPattern("#,##0.00");
        xNumberField2.setReadonly(true);
        panelRight.add(xNumberField2);
        xNumberField2.setBounds(12, 116, 206, 48);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Change:");
        panelRight.add(jLabel5);
        jLabel5.setBounds(12, 170, 158, 20);

        xNumberField3.setEditable(false);
        xNumberField3.setFieldType(BigDecimal.class);
        xNumberField3.setFont(new java.awt.Font("Tahoma", 1, 24));
        xNumberField3.setForeground(new java.awt.Color(204, 0, 0));
        xNumberField3.setIndex(100);
        xNumberField3.setName("entity.info.change");
        xNumberField3.setPattern("#,##0.00");
        xNumberField3.setReadonly(true);
        panelRight.add(xNumberField3);
        xNumberField3.setBounds(12, 196, 206, 48);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(230, 100));
        xActionBar1.setButtonPreferredSize(new java.awt.Dimension(85, 35));
        xActionBar1.setName("paymentoptions");
        xActionBar1.setOrientation("VERTICAL");
        xActionBar1.setPreferredSize(new java.awt.Dimension(65, 35));
        xActionBar1.setUseToolBar(false);
        jPanel5.add(xActionBar1, java.awt.BorderLayout.CENTER);

        panelRight.add(jPanel5);
        jPanel5.setBounds(10, 290, 210, 230);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel6.setText("Payment Options");
        panelRight.add(jLabel6);
        jLabel6.setBounds(10, 260, 210, 20);

        add(panelRight, java.awt.BorderLayout.EAST);

        bodyPanel.setLayout(new java.awt.BorderLayout());

        paymentsummaryPanel.setLayout(new java.awt.BorderLayout());

        paymentsummaryPanel.setPreferredSize(new java.awt.Dimension(200, 120));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Payment Summary");
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(137, 25));
        paymentsummaryPanel.add(jLabel7, java.awt.BorderLayout.NORTH);

        xDataTable1.setDynamic(true);
        xDataTable1.setHandler("paymentsummaryHandler");
        xDataTable1.setImmediate(true);
        paymentsummaryPanel.add(xDataTable1, java.awt.BorderLayout.CENTER);

        bodyPanel.add(paymentsummaryPanel, java.awt.BorderLayout.SOUTH);

        stubinfoPanel.setCaptionBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        stubinfoPanel.setCaptionFont(new java.awt.Font("Arial", 0, 12));
        stubinfoPanel.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        stubinfoPanel.setPadding(new java.awt.Insets(0, 8, 0, 8));
        stubinfoPanel.setPreferredSize(new java.awt.Dimension(0, 22));
        stubinfoPanel.setShowCaption(false);
        xLabel4.setCaption("AF No. ");
        xLabel4.setCaptionWidth(53);
        xLabel4.setFont(new java.awt.Font("Arial", 1, 14));
        xLabel4.setForeground(new java.awt.Color(204, 0, 0));
        xLabel4.setName("entity.info.afid");
        xLabel4.setPreferredSize(new java.awt.Dimension(60, 20));
        stubinfoPanel.add(xLabel4);

        xLabel7.setCaption("Serial No.");
        xLabel7.setCaptionWidth(68);
        xLabel7.setFont(new java.awt.Font("Arial", 1, 14));
        xLabel7.setForeground(new java.awt.Color(204, 0, 0));
        xLabel7.setName("entity.info.serialno");
        xLabel7.setPreferredSize(new java.awt.Dimension(150, 20));
        stubinfoPanel.add(xLabel7);

        xLabel10.setForeground(new java.awt.Color(204, 0, 0));
        xLabel10.setCaption("Stub No.");
        xLabel10.setCaptionWidth(63);
        xLabel10.setFont(new java.awt.Font("Arial", 1, 14));
        xLabel10.setName("entity.info.stubno");
        xLabel10.setPreferredSize(new java.awt.Dimension(100, 20));
        stubinfoPanel.add(xLabel10);

        xLabel8.setForeground(new java.awt.Color(204, 0, 0));
        xLabel8.setCaption("Mode");
        xLabel8.setCaptionWidth(45);
        xLabel8.setFont(new java.awt.Font("Arial", 1, 14));
        xLabel8.setName("entity.info.mode");
        xLabel8.setPreferredSize(new java.awt.Dimension(150, 20));
        stubinfoPanel.add(xLabel8);

        bodyPanel.add(stubinfoPanel, java.awt.BorderLayout.NORTH);

        add(bodyPanel, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel paymentsummaryPanel;
    private com.rameses.rcp.util.FormPanel stubinfoPanel;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XLabel xLabel10;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XNumberField xNumberField3;
    // End of variables declaration//GEN-END:variables
    
}
