{
	name: "Calculate SEF",
	template: "calculate-sef",
	params: [
		{ name:"ledger", datatype:'RPTLedgerFact', usevar:true, caption:'Ledger ID', required:true },
		{ name: "expr", datatype: 'string', caption: 'Computation Formula', expression:true },
		{ name: "sefacct", datatype: 'lookup', caption: 'Account Title', handler:'incomeaccount:lookup', itemKey:'objid', itemLabel:'title'},
		{ name: "revtype", datatype: "lookup", caption: "Revenue Period", handler:"rptrevtype:lookup", itemKey:"key", itemLabel:"value", required:true},
	]
}