/*
 * BurialPermitCollectionPage.java
 *
 * Created on March 26, 2013, 3:08 PM
 */

package com.rameses.gov.etracs.treasury.collection.burial;

import com.rameses.enterprise.treasury.collection.ui.CollectionPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  MS
 */
@StyleSheet
@Template(CollectionPage.class)
public class BurialPermitCollectionPage extends javax.swing.JPanel {
    
    /** Creates new form BurialPermitCollectionPage */
    public BurialPermitCollectionPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        jPanel6 = new javax.swing.JPanel();
        formPanel3 = new com.rameses.rcp.util.FormPanel();
        xTextField10 = new com.rameses.rcp.control.XTextField();
        xTextField11 = new com.rameses.rcp.control.XTextField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xTextField12 = new com.rameses.rcp.control.XTextField();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xTextField13 = new com.rameses.rcp.control.XTextField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        formPanel4 = new com.rameses.rcp.util.FormPanel();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();
        formPanel5 = new com.rameses.rcp.util.FormPanel();
        xTextField7 = new com.rameses.rcp.control.XTextField();
        xTextField8 = new com.rameses.rcp.control.XTextField();
        xTextField9 = new com.rameses.rcp.control.XTextField();

        setLayout(new java.awt.BorderLayout());

        formPanel1.setCaptionBorder(null);
        formPanel1.setCaptionFont(new java.awt.Font("Arial", 0, 12));
        formPanel1.setPadding(new java.awt.Insets(0, 8, 8, 8));
        xTextField1.setCaption("Paid By");
        xTextField1.setCaptionWidth(75);
        xTextField1.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField1.setName("entity.info.paidby");
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField1.setRequired(true);
        formPanel1.add(xTextField1);

        xTextField2.setCaption("Address");
        xTextField2.setCaptionWidth(75);
        xTextField2.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField2.setName("entity.info.paidbyaddress");
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField2.setRequired(true);
        formPanel1.add(xTextField2);

        xDateField1.setCaption("Txn Date ");
        xDateField1.setCaptionWidth(75);
        xDateField1.setDepends(new String[] {"af"});
        xDateField1.setFont(new java.awt.Font("Arial", 0, 12));
        xDateField1.setName("entity.info.txndate");
        xDateField1.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xDateField1);

        add(formPanel1, java.awt.BorderLayout.NORTH);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Burial Permit and License Fee Information");
        jPanel6.setBorder(xTitledBorder1);
        jPanel6.setPreferredSize(new java.awt.Dimension(566, 382));

        formPanel3.setCaptionFont(new java.awt.Font("Arial", 0, 12));
        formPanel3.setPadding(new java.awt.Insets(0, 5, 5, 5));
        xTextField10.setCaption("To City/Municipality of");
        xTextField10.setCaptionWidth(140);
        xTextField10.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField10.setName("entity.tocitymuni");
        xTextField10.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel3.add(xTextField10);

        xTextField11.setCaption("To Province");
        xTextField11.setCaptionWidth(140);
        xTextField11.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField11.setName("entity.toprovince");
        xTextField11.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel3.add(xTextField11);

        xComboBox1.setCaption("Permission Type");
        xComboBox1.setCaptionWidth(140);
        xComboBox1.setExpression("#{value}");
        xComboBox1.setFont(new java.awt.Font("Arial", 0, 12));
        xComboBox1.setItemKey("value");
        xComboBox1.setItems("permissionTypeList");
        xComboBox1.setName("entity.permissiontype");
        xComboBox1.setPreferredSize(new java.awt.Dimension(0, 19));
        xComboBox1.setRequired(true);
        formPanel3.add(xComboBox1);

        xTextField3.setCaption("Name");
        xTextField3.setCaptionWidth(140);
        xTextField3.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField3.setName("entity.name");
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField3.setRequired(true);
        formPanel3.add(xTextField3);

        xTextField4.setCaption("Nationality");
        xTextField4.setCaptionWidth(140);
        xTextField4.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField4.setName("entity.nationality");
        xTextField4.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel3.add(xTextField4);

        xTextField12.setCaption("Age");
        xTextField12.setCaptionWidth(140);
        xTextField12.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField12.setName("entity.age");
        xTextField12.setPreferredSize(new java.awt.Dimension(200, 19));
        formPanel3.add(xTextField12);

        xComboBox2.setCaption("Sex");
        xComboBox2.setCaptionWidth(140);
        xComboBox2.setExpression("#{value}");
        xComboBox2.setFont(new java.awt.Font("Arial", 0, 12));
        xComboBox2.setItemKey("value");
        xComboBox2.setItems("sexList");
        xComboBox2.setName("entity.sex");
        xComboBox2.setPreferredSize(new java.awt.Dimension(200, 19));
        xComboBox2.setRequired(true);
        formPanel3.add(xComboBox2);

        xTextField13.setCaption("Date of Death");
        xTextField13.setCaptionWidth(140);
        xTextField13.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField13.setName("entity.dtdeath");
        xTextField13.setPreferredSize(new java.awt.Dimension(200, 19));
        formPanel3.add(xTextField13);

        xTextField5.setCaption("Cause of Death");
        xTextField5.setCaptionWidth(140);
        xTextField5.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField5.setName("entity.deathcause");
        xTextField5.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel3.add(xTextField5);

        xTextField6.setCaption("Cemetery");
        xTextField6.setCaptionWidth(140);
        xTextField6.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField6.setName("entity.cemetery");
        xTextField6.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField6.setRequired(true);
        formPanel3.add(xTextField6);

        formPanel4.setAddCaptionColon(false);
        formPanel4.setCaptionBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        formPanel4.setCaptionFont(new java.awt.Font("Arial", 1, 12));
        formPanel4.setPadding(new java.awt.Insets(5, 0, 0, 0));
        formPanel4.setPreferredSize(new java.awt.Dimension(0, 150));
        formPanel4.setShowCaption(false);
        xSeparator1.setCaption("In case of disenterment");
        xSeparator1.setCaptionWidth(145);
        xSeparator1.setPreferredSize(new java.awt.Dimension(0, 20));
        xSeparator1.setShowCaption(true);
        org.jdesktop.layout.GroupLayout xSeparator1Layout = new org.jdesktop.layout.GroupLayout(xSeparator1);
        xSeparator1.setLayout(xSeparator1Layout);
        xSeparator1Layout.setHorizontalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 416, Short.MAX_VALUE)
        );
        xSeparator1Layout.setVerticalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 20, Short.MAX_VALUE)
        );
        formPanel4.add(xSeparator1);

        formPanel5.setCaptionFont(new java.awt.Font("Arial", 0, 12));
        formPanel5.setPadding(new java.awt.Insets(0, 20, 5, 5));
        formPanel5.setPreferredSize(new java.awt.Dimension(0, 150));
        formPanel5.setShowCaption(false);
        xTextField7.setCaption("Infectious or Non-Infectious");
        xTextField7.setCaptionWidth(230);
        xTextField7.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField7.setName("entity.infectious");
        xTextField7.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xTextField7);

        xTextField8.setCaption("Body embalmed or not embalmed");
        xTextField8.setCaptionWidth(230);
        xTextField8.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField8.setName("entity.embalmed");
        xTextField8.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xTextField8);

        xTextField9.setCaption("Disposition of remains");
        xTextField9.setCaptionWidth(230);
        xTextField9.setFont(new java.awt.Font("Arial", 0, 12));
        xTextField9.setName("entity.disposition");
        xTextField9.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel5.add(xTextField9);

        formPanel4.add(formPanel5);

        formPanel3.add(formPanel4);

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 571, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 341, Short.MAX_VALUE))
        );
        add(jPanel6, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel3;
    private com.rameses.rcp.util.FormPanel formPanel4;
    private com.rameses.rcp.util.FormPanel formPanel5;
    private javax.swing.JPanel jPanel6;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField10;
    private com.rameses.rcp.control.XTextField xTextField11;
    private com.rameses.rcp.control.XTextField xTextField12;
    private com.rameses.rcp.control.XTextField xTextField13;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    private com.rameses.rcp.control.XTextField xTextField7;
    private com.rameses.rcp.control.XTextField xTextField8;
    private com.rameses.rcp.control.XTextField xTextField9;
    // End of variables declaration//GEN-END:variables
    
}
