package com.rameses.gov.etracs.rpt.rule.billing;

import com.rameses.rules.common.*;
import java.util.*;

#--------------------------------------------------------------------------
# RULE PHASES
#---------------------------------------------------------------------------
rule "start-phase"
	auto-focus
	salience 100000
	no-loop
	then
    System.out.println("Start RPTBilling Computation...");
    drools.setFocus("TAX");
end

rule "end-tax"
   agenda-group "TAX"
   salience -100
   no-loop
   when
	  not CancelExecution()
   then
   System.out.println("Done computing tax...");
    drools.setFocus("PENALTY");
end

rule "end-penalty"
   agenda-group "PENALTY"
   salience -100
   no-loop
   when
	  not CancelExecution()
   then
    System.out.println("Done computing penalty...");
      drools.setFocus("DISCOUNT");
end

rule "end-discount"
   agenda-group "DISCOUNT"
   salience -100
   no-loop
   when
	  not CancelExecution()
   then
    System.out.println("Done computing discount...");
    System.out.println("Done executing RPT Billing rules.");
end
