package bpassessment;

import java.util.*;
import com.rameses.rules.common.*;
global RuleAction action;

rule "assert-variables"
	salience -100
	no-loop
	when
	then
		action.execute( "assert_sysvars", null, drools);
end

rule "assert-business-tax"
	agenda-group "businesstax"
	salience -100
	no-loop
	when
	then
		action.execute( "assert_taxfee", "TAX", drools);
end

rule "assert-regfee"
	agenda-group "regfee"
	salience -100
	no-loop
	when
	then
		action.execute( "assert_taxfee", "REGFEE", drools);
end

rule "assert-othercharge"
	agenda-group "othercharge"
	salience -100
	no-loop
	when
	then
		action.execute( "assert_taxfee", "OTHERCHARGE", drools);
end

