/*
 * ApplicationInitialPage.java
 *
 * Created on June 6, 2011, 1:20 PM
 */

package com.rameses.gov.etracs.mtop.application;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  MS
 */

@Template(FormPage.class)
public class ApplicationInitPageB extends javax.swing.JPanel {
    
    /** Creates new form ApplicationInitialPage */
    public ApplicationInitPageB() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xLabel3 = new com.rameses.rcp.control.XLabel();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(546, 229));
        jPanel1.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setFont(new java.awt.Font("Tahoma", 1, 11));
        xTitledBorder1.setTitle("MTOP Application");
        jPanel1.setBorder(xTitledBorder1);

        xLookupField1.setCaption("Franchise No.");
        xLookupField1.setExpression("#{application.franchiseno}");
        xLookupField1.setHandler("lookupApplication");
        xLookupField1.setPreferredSize(new java.awt.Dimension(200, 19));
        formPanel1.add(xLookupField1);

        com.rameses.rcp.control.border.XLineBorder xLineBorder1 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder1.setLineColor(new java.awt.Color(204, 204, 204));
        xLabel1.setBorder(xLineBorder1);
        xLabel1.setCaption("Owner");
        xLabel1.setCaptionFont(new java.awt.Font("Tahoma", 0, 11));
        xLabel1.setCaptionWidth(80);
        xLabel1.setExpression("#{application.owner.name}");
        xLabel1.setFont(new java.awt.Font("Tahoma", 0, 11));
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xLabel1);

        com.rameses.rcp.control.border.XLineBorder xLineBorder2 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder2.setLineColor(new java.awt.Color(204, 204, 204));
        xLabel4.setBorder(xLineBorder2);
        xLabel4.setCaption("Address");
        xLabel4.setCaptionFont(new java.awt.Font("Tahoma", 0, 11));
        xLabel4.setCaptionWidth(80);
        xLabel4.setExpression("#{application.owner.address}");
        xLabel4.setFont(new java.awt.Font("Tahoma", 0, 11));
        xLabel4.setPreferredSize(new java.awt.Dimension(0, 19));
        formPanel1.add(xLabel4);

        jPanel1.add(formPanel1);
        formPanel1.setBounds(0, 20, 490, 80);

        com.rameses.rcp.control.border.XLineBorder xLineBorder3 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder3.setLineColor(new java.awt.Color(204, 204, 204));
        xLabel2.setBorder(xLineBorder3);
        xLabel2.setCaption("Type");
        xLabel2.setCaptionFont(new java.awt.Font("Tahoma", 0, 11));
        xLabel2.setCaptionWidth(80);
        xLabel2.setExpression("#{application.txntype}");
        xLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        xLabel2.setName("application.txntype");
        xLabel2.setPreferredSize(new java.awt.Dimension(200, 19));
        formPanel2.add(xLabel2);

        com.rameses.rcp.control.border.XLineBorder xLineBorder4 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder4.setLineColor(new java.awt.Color(204, 204, 204));
        xLabel3.setBorder(xLineBorder4);
        xLabel3.setCaption("Mode");
        xLabel3.setCaptionFont(new java.awt.Font("Tahoma", 0, 11));
        xLabel3.setCaptionWidth(80);
        xLabel3.setExpression("#{application.txnmode}");
        xLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        xLabel3.setName("application.txnmode");
        xLabel3.setPreferredSize(new java.awt.Dimension(200, 19));
        formPanel2.add(xLabel3);

        jPanel1.add(formPanel2);
        formPanel2.setBounds(0, 110, 490, 60);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 500, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        add(jPanel2, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    // End of variables declaration//GEN-END:variables
    
}
