/*
 * RPTLedgerAddItemPage.java
 *
 * Created on July 2, 2011, 2:05 PM
 */

package com.rameses.gov.etracs.rpt.ledger.ui;

import java.math.BigDecimal;

/**
 *
 * @author  jzamora
 */
public class RPTLedgerFaasPage extends javax.swing.JPanel {
    
    /** Creates new form RPTLedgerAddItemPage */
    public RPTLedgerFaasPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();
        xCheckBox2 = new com.rameses.rcp.control.XCheckBox();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xButton1 = new com.rameses.rcp.control.XButton();
        xButton2 = new com.rameses.rcp.control.XButton();

        setPreferredSize(new java.awt.Dimension(349, 340));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("FAAS Information");
        formPanel1.setBorder(xTitledBorder1);
        xTextField1.setCaption("TD No.");
        xTextField1.setCaptionWidth(110);
        xTextField1.setName("ledgerfaas.tdno");
        xTextField1.setPreferredSize(new java.awt.Dimension(150, 19));
        xTextField1.setRequired(true);
        formPanel1.add(xTextField1);

        xComboBox1.setCaption("Txn Type");
        xComboBox1.setCaptionWidth(110);
        xComboBox1.setDynamic(true);
        xComboBox1.setExpression("#{item.objid}");
        xComboBox1.setItems("txntypes");
        xComboBox1.setName("ledgerfaas.txntype");
        xComboBox1.setPreferredSize(new java.awt.Dimension(150, 19));
        xComboBox1.setRequired(true);
        formPanel1.add(xComboBox1);

        xComboBox2.setCaption("Classification");
        xComboBox2.setCaptionWidth(110);
        xComboBox2.setExpression("#{item.name}");
        xComboBox2.setItems("classifications");
        xComboBox2.setName("ledgerfaas.classification");
        xComboBox2.setPreferredSize(new java.awt.Dimension(150, 19));
        xComboBox2.setRequired(true);
        formPanel1.add(xComboBox2);

        xCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox1.setCaption("");
        xCheckBox1.setCaptionWidth(110);
        xCheckBox1.setCellPadding(new java.awt.Insets(5, 0, 0, 0));
        xCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox1.setName("ledgerfaas.taxable");
        xCheckBox1.setPreferredSize(new java.awt.Dimension(150, 19));
        xCheckBox1.setText(" Taxable?");
        formPanel1.add(xCheckBox1);

        xCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox2.setCaption("");
        xCheckBox2.setCaptionWidth(110);
        xCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox2.setName("ledgerfaas.backtax");
        xCheckBox2.setPreferredSize(new java.awt.Dimension(150, 19));
        xCheckBox2.setText(" Back Tax?");
        formPanel1.add(xCheckBox2);

        xSeparator1.setPreferredSize(new java.awt.Dimension(0, 20));
        org.jdesktop.layout.GroupLayout xSeparator1Layout = new org.jdesktop.layout.GroupLayout(xSeparator1);
        xSeparator1.setLayout(xSeparator1Layout);
        xSeparator1Layout.setHorizontalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 315, Short.MAX_VALUE)
        );
        xSeparator1Layout.setVerticalGroup(
            xSeparator1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 20, Short.MAX_VALUE)
        );
        formPanel1.add(xSeparator1);

        xNumberField1.setCaption("From Year");
        xNumberField1.setCaptionWidth(110);
        xNumberField1.setFieldType(Integer.class);
        xNumberField1.setName("ledgerfaas.fromyear");
        xNumberField1.setPattern("0000");
        xNumberField1.setPreferredSize(new java.awt.Dimension(150, 19));
        xNumberField1.setRequired(true);
        formPanel1.add(xNumberField1);

        xComboBox3.setCaption("From Qtr");
        xComboBox3.setCaptionWidth(110);
        xComboBox3.setItems("quarters");
        xComboBox3.setName("ledgerfaas.fromqtr");
        xComboBox3.setPreferredSize(new java.awt.Dimension(150, 20));
        xComboBox3.setRequired(true);
        formPanel1.add(xComboBox3);

        xLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel1.setCaption("To Year");
        xLabel1.setCaptionWidth(110);
        xLabel1.setExpression("#{ledgerfaas.toyear}");
        xLabel1.setName("ledgerfaas.toyear");
        xLabel1.setPreferredSize(new java.awt.Dimension(150, 19));
        formPanel1.add(xLabel1);

        xLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel2.setCaption("To Qtr");
        xLabel2.setCaptionWidth(110);
        xLabel2.setExpression("#{ledgerfaas.toqtr}");
        xLabel2.setName("ledgerfaas.toyear");
        xLabel2.setPreferredSize(new java.awt.Dimension(150, 19));
        formPanel1.add(xLabel2);

        xNumberField2.setCaption("Assessed Value");
        xNumberField2.setCaptionWidth(110);
        xNumberField2.setFieldType(BigDecimal.class);
        xNumberField2.setName("ledgerfaas.assessedvalue");
        xNumberField2.setPattern("#,##0.00");
        xNumberField2.setPreferredSize(new java.awt.Dimension(150, 19));
        formPanel1.add(xNumberField2);

        xButton1.setMnemonic('c');
        xButton1.setImmediate(true);
        xButton1.setName("_close");
        xButton1.setText("Cancel");

        xButton2.setMnemonic('o');
        xButton2.setDefaultCommand(true);
        xButton2.setName("ok");
        xButton2.setText("OK");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(xButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(xButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(xButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(xButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XCheckBox xCheckBox2;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
    
}
