package rptbilling;

declare RPTLedgerFact
    objid                   : String
    rptledgerid             : String 
    tdno                    : String 
    year                    : Integer
    qtr                     : Integer 
    originalav              : Double
    av                      : Double
    txntype                 : String 
    rputype                 : String 
    barangayid              : String
    classification          : String
    actualuse               : String
    numberofmonthsfromqtr   : Integer
    numberofmonthsfromjan   : Integer
    firstqtrpaidontime      : Boolean
    qtrlypaymentavailed     : Boolean
    qtrlypaymentpaidontime : Boolean
    backtax                 : Boolean 
    fullpayment             : Boolean 
    advancepayment          : Boolean 
    basic                   : Double
    basicint                : Double
    basicdisc               : Double
    basiccredit             : Double
    basicamnesty            : Double
    basicintamnesty         : Double
    sef                     : Double
    sefint                  : Double
    sefdisc                 : Double
    sefcredit               : Double
    sefamnesty              : Double
    sefintamnesty           : Double
    firecode                : Double
    basicacctid           : String 
    basicintacctid        : String 
    sefacctid             : String 
    sefintacctid          : String 
    firecodeacctid        : String 

    lgushare                : Double
    lguintshare                : Double
    
    brgyshare               : Double
    brgyintshare            : Double
    brgyshareacctid         : String 
    brgyintshareacctid      : String 

    provshare               : Double
    provintshare            : Double
    provshareacctid         : String 
    provintshareacctid      : String 
    
    expr                  : String 
    paidyear              : Integer
    revtype               : String
    reclassed               :Boolean
end



declare AssessedValueFact
    rptledgerid   : String
    year          : Integer
    assessedvalue : Double 
    qtrlyav       : Double 
end


